GET http://127.0.0.1:3000/api/news?sources=abc-news

######

GET http://127.0.0.1:3000/api/news?sources=techcrunch&q=

######


GET http://127.0.0.1:3000/api/head-lines?country=MX

######
GET http://127.0.0.1:3000/api/sources?language=de


######

GET http://127.0.0.1:3000/api/sources-names

######